using System.Collections.Generic;

namespace BPD.Localization
{
    /// <summary>
    /// Lightweight EN string table with RU table reserved later (see locale_tables_PLACEHOLDER.json).
    /// Gameplay/UI code must call Loc.Get(key) instead of embedding copy.
    /// </summary>
    public static class Loc
    {
        static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            ["ui.action.left"] = "Left choice",
            ["ui.action.right"] = "Right choice",
            ["ui.action.skill"] = "DBT skill",
            ["ui.action.skill_charges"] = "{0} ({1})",
            ["ui.action.no_charges"] = "No DBT charges",
            ["ui.key.up"] = "↑",
            ["ui.key.left"] = "←",
            ["ui.key.right"] = "→",
            ["ui.key.down"] = "↓",
            ["ui.key.hint"] = "{0}  {1}",
            ["ui.level.header"] = "Level {0}",
            ["ui.level.xp"] = "Level XP: {0} / {1}",
            ["ui.therapy.select_hint"] = "Step 1 Situation+Thought, then Step 2 Emotion+Behavior.",
            ["ui.meta.impulsivity"] = "Impulsivity severity: {0} / {1}",
            ["ui.meta.symptom_severity"] = "Severity: {0} / {1}",
            ["ui.meta.memories"] = "Memories: {0}",
            ["ui.brand"] = "PLACEHOLDER Title",
            ["ui.character.select"] = "Choose a background",
            ["ui.character.a"] = "Character A — family wealth, emotional abuse",
            ["ui.character.b"] = "Character B — high-functioning burnout",
            ["ui.character.c"] = "Character C — survival under stigma",
            ["ui.stat.wholeness"] = "Wholeness",
            ["ui.stat.stability"] = "Stability",
            ["ui.stat.safety"] = "Safety",
            ["ui.stat.closeness"] = "Closeness",
            ["ui.level.swipe_hint"] = "Swipe / drag  ·  ← left  ·  → right",
            ["ui.level.swipe_hint_skill"] = "Swipe / drag  ·  ← left  ·  → right  ·  ↑ DBT skill",
            ["ui.level.win"] = "Level complete",
            ["ui.level.lose"] = "Crisis — Split begins",
            ["ui.meta.title"] = "Spend XP · Skills · Therapy",
            ["ui.meta.xp"] = "Unspent XP: {0}",
            ["ui.meta.reduce_symptom"] = "Reduce {0} (-1 XP cost)",
            ["ui.meta.next_symptom"] = "Next symptom",
            ["ui.meta.symptom_tree"] = "Symptom tree — tap to select",
            ["ui.meta.symptom_row"] = "{0}  {1}  {2}/{3}",
            ["ui.meta.therapy"] = "Open Therapy",
            ["ui.meta.next_level"] = "Next Level",
            ["ui.meta.skill_unlocked"] = "Unlocked: {0}\n{1}",
            ["ui.meta.controls_hint"] = "↑ reduce  ·  ← therapy  ·  → next level",
            ["ui.split.success"] = "You held on",
            ["ui.split.fail"] = "Collapse — restart this level",
            ["ui.split.btn_success"] = "Practice the skill",
            ["ui.split.btn_fail"] = "Collapse",
            ["ui.split.btn_skill"] = "Practice the skill",
            ["ui.split.btn.stop"] = "STOP — pause",
            ["ui.split.btn.facts"] = "Check the facts",
            ["ui.split.btn.wise"] = "Seek Wise Mind",
            ["ui.split.btn.dearman"] = "Ask with DEAR MAN",
            ["ui.split.step"] = "Step {0} / {1}",
            ["ui.split.controls_hint"] = "← practice skill  ·  → collapse",
            ["ui.split.edu.safety"] = "Crisis skill focus: STOP — pause before the urge chooses.",
            ["ui.split.edu.stability"] = "Emotion skill focus: Check the Facts — does the feeling fit what is happening?",
            ["ui.split.edu.wholeness"] = "Mindfulness focus: Wise Mind — emotion and reason can meet.",
            ["ui.split.edu.closeness"] = "Interpersonal focus: DEAR MAN — ask clearly without disappearing.",
            ["ui.crisis.resources"] = "If you are in crisis, contact local emergency services or a trusted crisis line. This game is educational — not a substitute for therapy or medical care.",
            ["ui.therapy.title"] = "Therapy merge",
            ["ui.therapy.merge"] = "Merge selected",
            ["ui.therapy.back"] = "Back",
            ["ui.therapy.result"] = "Merged: {0}",
            ["ui.therapy.memory"] = "Memory unlocked (Stability penalty next level)",
            ["ui.therapy.phase_emotion"] = "Step 1 — pair a Situation with a Thought",
            ["ui.therapy.phase_need"] = "Step 2 — pair the Emotion with a Behavior",
            ["ui.therapy.controls_hint"] = "Tap board to select · → merge · ← back",
            ["ui.therapy.selected"] = "Selected: {0}",
            ["ui.therapy.selected_mark"] = "✓ {0}",
            ["ui.therapy.unlocked_emotion"] = "Unlocked emotion: {0}\nNext: pair it with a Behavior to unlock a skill.",
            ["ui.therapy.unlocked_need"] = "Unlocked need: {0}",
            ["ui.therapy.new_chain"] = "New chain (Situation+Thought)",
            ["ui.therapy.use_emotions"] = "Use unlocked emotions",
            ["ui.therapy.col_situation"] = "Situation",
            ["ui.therapy.col_thought"] = "Thought",
            ["ui.therapy.col_behavior"] = "Behavior",
            ["ui.therapy.col_emotion"] = "Emotion",
            ["ui.therapy.locked_emotion"] = "Emotion: [Locked]",
            ["ui.therapy.locked_need"] = "Need: [Locked]",
            ["ui.therapy.slot_emotion"] = "Emotion: {0}",
            ["ui.therapy.slot_need"] = "Need: {0}",
            ["ui.character.controls_hint"] = "↑ A  ·  ← B  ·  → C",
            ["ui.ending.restart"] = "Begin again",
            ["ui.ending.hint"] = "↑ restart",

            ["symptom.fear_abandonment.name"] = "Fear of abandonment",
            ["symptom.fear_abandonment.edu"] = "Educational: frantic efforts to avoid real or imagined abandonment.",
            ["symptom.fear_abandonment.mod"] = "Lower severity softens Closeness losses.",
            ["symptom.unstable_relationships.name"] = "Unstable relationships",
            ["symptom.unstable_relationships.edu"] = "Educational: intense relationships that swing between idealization and devaluation.",
            ["symptom.unstable_relationships.mod"] = "Lower severity softens relationship swings.",
            ["symptom.unstable_self.name"] = "Unstable self-image",
            ["symptom.unstable_self.edu"] = "Educational: a shifting sense of who you are.",
            ["symptom.unstable_self.mod"] = "Lower severity softens Wholeness losses.",
            ["symptom.impulsivity.name"] = "Impulsivity",
            ["symptom.impulsivity.edu"] = "Educational: acting on urges that can cause harm.",
            ["symptom.impulsivity.mod"] = "Lower severity softens Safety losses.",
            ["symptom.self_harm.name"] = "Self-harm / suicidality themes",
            ["symptom.self_harm.edu"] = "Educational: crisis urges routed through Safety — without sensationalism.",
            ["symptom.self_harm.mod"] = "Lower severity softens Safety crisis pull.",
            ["symptom.affective.name"] = "Affective instability",
            ["symptom.affective.edu"] = "Educational: moods that rise and fall quickly.",
            ["symptom.affective.mod"] = "Lower severity softens Stability losses.",
            ["symptom.emptiness.name"] = "Chronic emptiness",
            ["symptom.emptiness.edu"] = "Educational: a hollow feeling that skills can sit beside, not erase.",
            ["symptom.emptiness.mod"] = "Lower severity adds a small Wholeness bonus on skill choices.",
            ["symptom.anger.name"] = "Intense anger",
            ["symptom.anger.edu"] = "Educational: anger that feels too big for the moment.",
            ["symptom.anger.mod"] = "Lower severity softens Closeness and Stability hits.",
            ["symptom.paranoia.name"] = "Paranoia / dissociation under stress",
            ["symptom.paranoia.edu"] = "Educational: stress can scramble trust in what is real.",
            ["symptom.paranoia.mod"] = "Lower severity softens Stability losses under stress.",

            ["split.safety.title"] = "The Urge Crest",
            ["split.safety.prompt"] = "The wave is high. Your body wants a fast exit. You can stop, step back, observe, and choose the next breath without turning the crisis into damage.",
            ["split.safety.step1"] = "STOP: freeze the next action. Feel your feet on the floor.",
            ["split.safety.step2"] = "Take a step back from the urge. Name it without obeying it.",
            ["split.safety.step3"] = "Observe the crest. Choose one breath, then the next wise step.",
            ["split.stability.title"] = "Flood and Fog",
            ["split.stability.prompt"] = "Feelings arrive stacked and loud. Names blur. Pause long enough to check the facts of this moment — not the catastrophe story.",
            ["split.stability.step1"] = "Name the emotion without the story attached.",
            ["split.stability.step2"] = "List facts you can verify right now.",
            ["split.stability.step3"] = "Ask: does the feeling fit these facts, or a feared future?",
            ["split.wholeness.title"] = "Scattered Pieces",
            ["split.wholeness.prompt"] = "Parts of you pull in opposite directions. You do not need to be finished to hold both — seek the middle where feeling and thinking can share a decision.",
            ["split.wholeness.step1"] = "Notice Emotion Mind pulling hard.",
            ["split.wholeness.step2"] = "Notice Reason Mind arguing back.",
            ["split.wholeness.step3"] = "Find Wise Mind: what honors both without abandoning either?",
            ["split.closeness.title"] = "Too Far / Too Close",
            ["split.closeness.prompt"] = "Someone matters and that terrifies you. You can describe what you need, express the feeling, and ask — without vanishing or clinging.",
            ["split.closeness.step1"] = "Describe the situation without blame.",
            ["split.closeness.step2"] = "Express the feeling and assert one clear need.",
            ["split.closeness.step3"] = "Reinforce and stay mindful — negotiate without disappearing.",

            ["ending.safety.title"] = "A Life With Urges",
            ["ending.safety.body"] = "You learned that an urge can crest without becoming the whole story. Crisis skills do not erase intensity — they give you a gap where a wiser next step can fit. You are still here. That counts.",
            ["ending.stability.title"] = "Feeling Without Drowning",
            ["ending.stability.body"] = "Emotions rose and fell. Naming them did not make you weak; it made the fog thinner. Recovery is not a straight line — returning to a skill after a hard day is still progress.",
            ["ending.wholeness.title"] = "Many Truths at Once",
            ["ending.wholeness.body"] = "You are not a single verdict. Hurt and hope can sit together. Building a life worth living is not becoming someone else — it is practicing holding more than one true thing.",
            ["ending.closeness.title"] = "Relating, Imperfectly",
            ["ending.closeness.body"] = "Connection asked for boundaries, clarity, and repair. You practiced asking without disappearing and caring without fusing. Imperfect closeness is still closeness.",
            ["ending.safety.body.a"] = "Wealth and pressure taught you to perform calm while urges ran underneath. Crisis skills do not erase intensity — they give you a gap. You are still here. That counts.",
            ["ending.safety.body.b"] = "Burnout taught you to push through until the body screamed. An urge can crest without becoming the whole story. You are still here. That counts.",
            ["ending.safety.body.c"] = "Stigma taught you to hide need until it exploded. Crisis skills offer a pause before damage. You are still here. That counts.",
            ["ending.stability.body.a"] = "Emotions rose and fell in a house where logic was armor. Naming them thinned the fog — recovery is not a straight line.",
            ["ending.stability.body.b"] = "High-functioning did not mean regulated. Naming feelings made the fog thinner; hard days still happen.",
            ["ending.stability.body.c"] = "Survival mode kept feelings loud and unnamed. You practiced checking facts and naming emotion — that is progress.",
            ["ending.wholeness.body.a"] = "Parts of you learned to split early. Hurt and hope can sit together — a life worth living is built in ordinary days.",
            ["ending.wholeness.body.b"] = "You held many roles at once. You are not a single verdict — integration is practice, not perfection.",
            ["ending.wholeness.body.c"] = "You learned to shrink to stay safe. Many truths can be true at once; you can hold more than one story.",
            ["ending.closeness.body.a"] = "Love and fear arrived together. You practiced asking with boundaries — imperfect closeness is still closeness.",
            ["ending.closeness.body.b"] = "Work crowded out connection until loneliness hurt. Repair and clarity are skills you can return to.",
            ["ending.closeness.body.c"] = "Rejection felt lethal. You practiced DEAR MAN and repair — relating imperfectly still counts.",

            ["therapy.stub.situation.01"] = "A plan changes without warning",
            ["therapy.stub.thought.01"] = "They will leave if I show need",
            ["therapy.stub.behavior.01"] = "You draft a careful message, then delete it",
            ["therapy.stub.emotion.01"] = "Fear-of-abandonment surge",
            ["therapy.stub.need.01"] = "Need: reassurance with boundaries",
            ["therapy.stub.situation.02"] = "Evening emptiness arrives",
            ["therapy.stub.thought.02"] = "Nothing will ever feel real again",
            ["therapy.stub.behavior.02"] = "You pace and refresh the same feed",
            ["therapy.stub.emotion.02"] = "Hollow ache",
            ["therapy.stub.need.02"] = "Need: present-moment contact",
            ["therapy.stub.situation.03"] = "Someone misreads your tone",
            ["therapy.stub.thought.03"] = "I always ruin connection",
            ["therapy.stub.behavior.03"] = "You shut down mid-conversation",
            ["therapy.stub.emotion.03"] = "Shame heat",
            ["therapy.stub.need.03"] = "Need: repair and clarity",
            ["therapy.error.null"] = "Select two cards",
            ["therapy.error.no_emotion_recipe"] = "No emotion recipe",
            ["therapy.error.emotion_locked"] = "Emotion still locked",
            ["therapy.error.no_need_recipe"] = "No need recipe",
            ["therapy.error.invalid_pair"] = "Invalid pair",
            ["card.stub.001.situation"] = "PLACEHOLDER: A message lights up. Your chest tightens.",
            ["card.stub.001.left"] = "Answer immediately",
            ["card.stub.001.right"] = "Wait and breathe",
            ["card.stub.001.skill"] = "Wise Mind pause",
            ["card.stub.002.situation"] = "PLACEHOLDER: Plans change without warning.",
            ["card.stub.002.left"] = "Push closer",
            ["card.stub.002.right"] = "Withdraw",
            ["card.stub.002.skill"] = "Check the Facts",
            ["card.stub.003.situation"] = "PLACEHOLDER: Emptiness arrives mid-afternoon.",
            ["card.stub.003.left"] = "Reach for a rush",
            ["card.stub.003.right"] = "Name the feeling",
            ["card.stub.003.skill"] = "Opposite Action",
            ["card.stub.004.situation"] = "PLACEHOLDER: Someone misunderstands you.",
            ["card.stub.004.left"] = "Defend hard",
            ["card.stub.004.right"] = "Ask for clarity",
            ["card.stub.004.skill"] = "DEAR MAN",
            ["card.stub.005.situation"] = "PLACEHOLDER: Night falls. The urge is loud.",
            ["card.stub.005.left"] = "Act on the urge",
            ["card.stub.005.right"] = "Urge surf",
            ["card.stub.005.skill"] = "STOP"
        };

        public static string Get(string key)
        {
            if (string.IsNullOrEmpty(key))
            {
                return string.Empty;
            }

            return En.TryGetValue(key, out var value) ? value : $"[{key}]";
        }

        public static string Format(string key, params object[] args)
        {
            return string.Format(Get(key), args);
        }
    }
}
